# .github/workflows/use-manual-other-repo.yml
name: Use Reusable Manual Workflow in Another Repo

on:
  push:
    branches:
      - master  # Trigger when pushing to the main branch

jobs:
  call-reusable-workflow:
    uses: pritamcdac/Calculator-githubact/.github/workflows/main.yml@main  # Replace with your repo and branch
    with:
      java_version: "11"  # Input value passed to the reusable workflow
