name: POC 2 - Variables in Workflow
on:
  push:
    branches:
      - master
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run external script
        run: |
          chmod +x scripts/example.sh
          ./scripts/example.sh
