name: POC 2 - Variables in Workflowp
on:
  push:
    branches:
      - master
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run external script
        run: |
          chmod +x scripts/example.sh
           ./scripts/example.sh
        
