name: POC 3 - Share Data Between Jobs
on:
  push:
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "Shared Data" > shared-file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shared-artifact
          path: shared-file.txt

  use-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: shared-artifact
      - name: Print file content
        run: cat shared-file.txt
